#!/usr/bin/env python
# coding: utf-8

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from firebase import firebase
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier

diabetes = pd.read_csv('/Users/satvikeltepu/Desktop/diabetes.csv')

X_train, X_test, Y_train, Y_test = train_test_split(
    diabetes.loc[:, diabetes.columns != 'Outcome'],
    diabetes['Outcome'],
    stratify=diabetes['Outcome'],
    random_state=66
)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

tree = DecisionTreeClassifier(criterion='entropy', random_state=0)
tree.fit(X_train, Y_train)

data = int(input("Enter data: "))
prediction = tree.predict(X_test[[data]])
print(prediction)

firebase = firebase.FirebaseApplication("https://diabetes-857d7.firebaseio.com/", None)
data = {
    'Diabetes': prediction.tolist(),
}

result = firebase.put("testdata", "LWEis88nRrBK6fJyFHUt", data)
print(result)
